
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Share2, Twitter, Facebook, Link, Download } from "lucide-react";
import { toast } from "sonner";

interface MoodRecommendation {
  id: string;
  timestamp: Date;
  userInput: string;
  moodSummary: string;
  musicVibe: string;
  youtubeSearch: string;
  spotifySearch: string;
  appleMusicSearch: string;
  recommendations: string[];
}

interface SharingOptionsProps {
  recommendation: MoodRecommendation;
}

const SharingOptions = ({ recommendation }: SharingOptionsProps) => {
  const generateShareText = () => {
    return `🎵 My current vibe: ${recommendation.moodSummary}\n🎶 Perfect music match: ${recommendation.musicVibe}\n\nGenerated by Music Vibe Assistant ✨`;
  };

  const shareToTwitter = () => {
    const text = generateShareText();
    const url = `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}`;
    window.open(url, '_blank');
  };

  const shareToFacebook = () => {
    const text = generateShareText();
    const url = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(window.location.href)}&quote=${encodeURIComponent(text)}`;
    window.open(url, '_blank');
  };

  const copyShareLink = async () => {
    const shareText = generateShareText();
    try {
      await navigator.clipboard.writeText(shareText);
      toast.success("Share text copied to clipboard!");
    } catch (err) {
      toast.error("Failed to copy share text");
    }
  };

  const downloadRecommendation = () => {
    const data = {
      timestamp: recommendation.timestamp.toISOString(),
      mood: recommendation.moodSummary,
      musicVibe: recommendation.musicVibe,
      platforms: {
        youtube: recommendation.youtubeSearch,
        spotify: recommendation.spotifySearch,
        appleMusic: recommendation.appleMusicSearch
      },
      recommendations: recommendation.recommendations
    };

    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `mood-recommendation-${recommendation.id}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast.success("Recommendation downloaded!");
  };

  return (
    <Card className="bg-gradient-to-r from-blue-50 to-indigo-50 border-blue-200">
      <CardContent className="p-4">
        <div className="flex items-center mb-3">
          <Share2 className="w-5 h-5 text-blue-600 mr-2" />
          <h3 className="font-semibold text-blue-800">Share Your Vibe</h3>
        </div>
        
        <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
          <Button
            onClick={shareToTwitter}
            variant="outline"
            size="sm"
            className="flex items-center justify-center border-blue-300"
          >
            <Twitter className="w-4 h-4 mr-1" />
            Twitter
          </Button>
          
          <Button
            onClick={shareToFacebook}
            variant="outline"
            size="sm"
            className="flex items-center justify-center border-blue-300"
          >
            <Facebook className="w-4 h-4 mr-1" />
            Facebook
          </Button>
          
          <Button
            onClick={copyShareLink}
            variant="outline"
            size="sm"
            className="flex items-center justify-center border-blue-300"
          >
            <Link className="w-4 h-4 mr-1" />
            Copy
          </Button>
          
          <Button
            onClick={downloadRecommendation}
            variant="outline"
            size="sm"
            className="flex items-center justify-center border-blue-300"
          >
            <Download className="w-4 h-4 mr-1" />
            Save
          </Button>
        </div>
        
        <div className="mt-3 p-2 bg-white/60 rounded text-xs text-blue-700">
          💡 <strong>Hackathon Feature:</strong> Share your mood discoveries and build a community around music & emotions!
        </div>
      </CardContent>
    </Card>
  );
};

export default SharingOptions;
